name: playground
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  lints: ^2.0.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  test: ^1.21.0
