name: add-urgent-issue-automation

on:
  issues:
    types: [labeled]
    
env:
  BOARD_NAME: "Board"

jobs:
  move-new-p0-issue-to-urgent-items:
    # Only issue with an P0 label should be moved to the urgent column
    if: contains(github.event.issues.labels.*.name, 'P0')
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.0
        with:
          project: ${{ env.BOARD_NAME }}
          column: "Urgent items"
          # The normal GITHUB_TOKEN should have enough permission to edit the board. However, it seems so, 
          # that there is a GitHub bug. As a workaround we add an Personal GitHub Token (Nils Token)
          repo-token: ${{ secrets.PROJECT_AUTOMATION_PLUS_TOKEN }}
  
