
name: closed-issue-automation

on:
  issues:
    types: [closed]
    
env:
  BOARD_NAME: "Board"

jobs:
  move-new-issues-to-backlog:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.0
        with:
          project: ${{ env.BOARD_NAME }}
          column: "Done"
          # The normal GITHUB_TOKEN should have enough permission to edit the board. However, it seems so, 
          # that there is a GitHub bug. As a workaround we add an Personal GitHub Token (Nils Token)
          repo-token: ${{ secrets.PROJECT_AUTOMATION_PLUS_TOKEN }}
