name: Camera testing

on: [ push ]

jobs:
  integration-test:
    # Is recommended to run job with macOS to take advantage of hardware
    # acceleration support provided by HAXM.
    runs-on: macos-latest
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        api-level: [28]
        target: [playstore]
        arch: [x86_64]
    steps:
      - uses: actions/checkout@v3
      - name: Java 15
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Open camera
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_3a
          sdcard-path-or-size: 512M
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back virtualscene -camera-front emulated
          script: |
            # Ensure emulator is ready 
            sleep 10
            
            # Start recording
            mkdir captures
            adb shell screenrecord /sdcard/recording.m4v &
            RECORD_PID=$!

            # Grant camera & location permission
            adb shell pm grant com.android.camera2 android.permission.ACCESS_COARSE_LOCATION

            # Open camera
            adb shell am start -a android.media.action.IMAGE_CAPTURE
            adb shell am start -a android.media.action.STILL_IMAGE_CAMERA

            # Click next on welcome screen
            sleep 5
            adb shell input tap 530 1918

            # Make screenshots
            sleep 5
            adb shell screencap -p > captures/1.jpg

            kill $RECORD_PID
            adb pull /sdcard/recording.m4v ./captures
      - name: Upload captures
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: captures_${{ matrix.target }}_${{ matrix.arch }}_${{ matrix.api-level }}
          path: ./captures