name: Camera testing

on: [ push ]

jobs:
  integration-test:
    # Is recommended to run job with macOS to take advantage of hardware
    # acceleration support provided by HAXM.
    runs-on: macos-latest
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        api-level: [32, 31, 30, 29, 28]
        target: [playstore]
        arch: [x86_64]
    steps:
      - uses: actions/checkout@v3
      - name: Java 15
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Open camera
        uses: nilsreichardt/android-emulator-runner@hot-fix-pre-emulator-launch-script
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_3a
          sdcard-path-or-size: 512M
          pre-emulator-launch-script: |
            # Insert QR Code image from "integration_test/qr_code.jpg" into the Android
            # camera emulator.
            # 
            # Source: https://stackoverflow.com/a/64922184/8358501
            echo "" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            echo "poster qr_code" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            echo "size 2 2" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            echo "position 0 0 -1.8" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            echo "rotation 0 0 0" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            echo "default qr_code.jpg" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            mv example/qr_code.jpg ~/Library/Android/sdk/emulator/resources/
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back virtualscene -camera-front emulated
          script: .github/workflows/script.sh
      - name: Upload captures
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: captures_${{ matrix.target }}_${{ matrix.arch }}_${{ matrix.api-level }}
          path: ./captures