name: arm64-v8a testing

on: [ push ]

jobs:
  integration-test:
    # Is recommended to run job with macOS to take advantage of hardware
    # acceleration support provided by HAXM.
    runs-on: macos-latest
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        api-level: [32, 31, 30, 29, 28, 27, 26, 25, 24]
        target: [playstore, default, google_apis]
        arch: [arm64-v8a]
    steps:
      - uses: actions/checkout@v3
      - name: Java 15
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Open camera
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_3a
          script: echo "booted!"