name: stable

on:
  workflow_dispatch:
    inputs:
      bump-version-after-release:
        type: boolean
        description: |
          Whether to bump the version after the release. TestFlight versions need
          to be newer than the App Store versions. This is why we need to bump the
          version after the stable release.

permissions: {}

jobs:
  bump-version:
    if: github.event.inputs.bump-version-after-release == 'true'
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: {
        contents: write,
        pull-requests: write
    }
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install cider
        run: dart pub global activate cider 0.2.7

      - name: Bump version
        working-directory: flutter_macos_flavors
        run: |
          VERSION=$(cider bump patch)
          echo "New version: $VERSION"
          git checkout -b "pump-version-$VERSION"
          git add pubspec.yaml
          git commit -m "Bump app version to $VERSION"

      - name: Create Pull Request
        run: gh pr create --fill
