name: test

on:
  push:

jobs:
  integration-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: master
        flutter-version: cb68d61
        git-source: https://github.com/nilsreichardt/flutter.git
    - run: flutter --version
    - name: Run Integration Test
      working-directory: integration_test_timeout 
      run: flutter test integration_test -d macos
