name: stable

on:
  workflow_dispatch:
    inputs:
      ios-changelog:
        type: string
        description: |
          The changelog for the iOS release. This will be used as the release
          notes in the App Store release and is required to deploy a new iOS
          version. If the changelog is not provided, the deployment for iOS will
          be skipped.

jobs:
  deploy-ios:
    # We skip the deployment if no changelog is provided because we assume that
    # nothing has changed in the iOS app and therefore no new version is needed.
    if: github.event.inputs.ios-changelog != ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Print changelog
        run: echo "${{ github.event.inputs.ios-changelog }}"
